### ISSUE TITLE
Reference to motion photos being lost when stacked

### ISSUE THREAD

**Issue by Tonux599** [mattdavis90/immich-stacker#4]
This could be an issue with the API, but I have no way to verify that. However this does not occur when manually stacking two images (one being RAW, another a JPG with a motion file).

After bulk stacking images with this tool, images that had motion no longer did. I could get Immich to "re-recognise" it had motion by re-scanning the metadata, but then when playing it it reports "No video with supported format and MIME type found".

So it seems that the reference to the motion video file seems to be removed when stacking. Un-stacking does not resolve this. Like I said may not be fault of the tool but maybe a fault in the API.

Thanks for this project though, keeping my library much tidier!

**Comment by mattdavis90** [comment]
Thanks for the report. I don't have any images with motion so haven't come across this. Are the motion JPEGs from an Android or iPhone? I'm not sure my camera can produce them so trying to think how I'll recreate the situation. If manually stacking in the UI works then hopefully there's a set of API calls to work around the issue

**Comment by mattdavis90** [comment]
I found [this post](https://github.com/photoprism/photoprism/issues/439) talking about live photos and they link to a [sample file](https://user-images.githubusercontent.com/1412303/92759077-a3ab3200-f38f-11ea-898c-8bf633cc9a20.jpg)

I'll have a go with that and see how I get on

**Comment by mattdavis90** [comment]
I've just had a play around and it appears that Immich stores a reference to the MP4 video as a field called `LivePhotoVideoId` - this is attached to your JPG images but not your RAW image. When I set the JPG as the parent then the Live Photo seems to work as expected, but if I set the RAW as the parent then the Live Photo icon disappears and I have to manually choose the JPG before it will play. There isn't an API call available to re-parent the Live Photo so I think the only real option is to have the JPG as the stack parent. Hope this helps

**Comment by mattdavis90** [comment]
Ignore the actual images. I just grabbed some samples from the internet and deliberately chose a RAW image that wasn't the same as the JPG so it is obvious which is which.

The RAW is the car, the JPG (with motion) is the city.

This shows the two images unstacked.

![Screenshot from 2024-08-25 20-57-19](https://github.com/user-attachments/assets/8294a384-ed13-44a3-b936-01a314c13a60)

Stacked with the RAW as the parent - note the lack of motion icon (this is the same via immich-stacker and the UI)

![Screenshot from 2024-08-25 20-57-33](https://github.com/user-attachments/assets/57795714-5974-41da-b15c-06f6202be832)

Zoom showing the option to switch back to the motion clip

![Screenshot from 2024-08-25 20-57-44](https://github.com/user-attachments/assets/63caf14d-21db-4a25-a285-61789125a6f3)

Stacked the other way and the icon is back - this is consistent both via the UI and immich-stacker

![Screenshot from 2024-08-25 20-58-03](https://github.com/user-attachments/assets/6b755374-c4a8-45a0-ba2b-836361e1e283)

**Comment by mattdavis90** [comment]
No problem. Happy to help. I only tested with these two images so its totally possible there's something odd going on. I don't think my Android phone can shoot RAW plus motion but I'll see if I can replicate your issue.

**Comment by mattdavis90** [comment]
Hi, I've tried a couple times and I'm unable to replicate what you're seeing. It definitely makes a difference which image is the parent but from testing if you have the JPG as parent then it seems to function as expected. Did you get anywhere with your testing?

**Comment by mattdavis90** [comment]
No problem. Feel free to reopen if you find you're still having issues after the refresh
