### ISSUE TITLE
Provide a way to disable TLS certificate checking

### ISSUE THREAD

**Issue by pr10dr** [mattdavis90/immich-stacker#6]
When targeting my local immich setup which does not provide a valid TLS certificate the process stops with this log

```
2024-10-21T07:00:22Z INF Connecting to Immich endpoint=https://192.168.XXX.XXX/api

2024-10-21T07:00:22Z FTL error="Get \"https://192.168.XXX.XXX/api/server/version\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.XXX.XXX because it doesn't contain any IP SANs"
```

as the target immich installation does not have a certificate setup thats to be expected.
The feature request is as follows: Please provide a way to disable tls checks when connecting to immich api.

Let me end this request with a big thank you for a great feature that will bring my immich adaption very much forward as currently jpeg / raw duplication is not ideal. Thanks!

**Comment by mattdavis90** [comment]
Hi, I just push v1.3.0 which adds a new environmental variable `IMMICH_INSECURE_TLS` - if you set that to true then you should be good to go :)

**Comment by mattdavis90** [comment]
Hi, did this solve your issue?

**Comment by pr10dr** [comment]
Hi matt, yes indeed the connection issue is solved! Thanks for your fast response.
I thought i already gave feedback here. Thanks for letting me know. Have a great day!
